# Generated by Django 4.2.3 on 2023-07-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApi', '0004_category_status_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetracking',
            name='income',
        ),
        migrations.AddField(
            model_name='incometracking',
            name='income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TrackerApi.expensetracking'),
        ),
        migrations.AddField(
            model_name='incometracking',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
