# Generated by Django 4.2.3 on 2023-07-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApi', '0008_alter_incometracking_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
