# Generated by Django 4.2.3 on 2023-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApi', '0009_billing_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_description',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
