# Generated by Django 4.2.3 on 2023-08-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApi', '0011_billing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TrackerApi.category'),
        ),
    ]
